server:
  port: 8080
  servlet:
    context-path: /wanghuan
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghuan?useSSL=false&amp;characterEncoding=utf-8&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    jedis:
      pool:
        max-idle: 300
        max-active: 300 
        max-wait: 1000
    timeout: 1000
mybatis:
  mapper-locations: classpath:com/wanghuan/dao/mapper/*.xml
  type-aliases-package: com.wanghuan.model
debug: true
logging:
  level:
    com.wanghuan: DEBUG
    org.springframework: WARN
    org.spring.springboot.dao: DEBUG
    